# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UI_ypcdhWC99wIJ5ABu6NE11XsYF_C8w
"""

import pandas as pd
import numpy as np
df = pd.DataFrame({
    "date": ["2025-01-01","2025-01-02","2025-01-03","2025-01-03","2025-01-04","2025-01-05","2025/01/06"],
    "pm25": [45.0,np.nan,999,52.0,-10,48.0,47.0],
    "station": ["BKK01","BKK01","BKK01","BKK01","BKK01","bkk01","BKK01"],
    "tavg" : [27.5,28.0,27.8,27.8,28.2,27.9,28.1],
    "prcp" : [0.0,0.0,0.0,0.0,-5,0.0,0.0]

})

# ตรวจ missing
print(df.isnull().sum())

display(df)

data_pm25 = df.pm25

Q1 = data_pm25.quantile(0.25)
Q3 = data_pm25.quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers =  data_pm25[( data_pm25 < lower) | ( data_pm25 > upper)]
print("outliers ที่พบ")
print(outliers)

import numpy as np
#เปลี่ยนค่าoutlierให้เป็นnull
df.loc[(df['pm25'] < lower) | (df['pm25'] > upper), 'pm25'] = np.nan
#ปรับค่าให้อยู่ในรูปแบบเดียวกัน
df['station'] = df['station'].str.upper()
df['date'] = pd.to_datetime(df['date'], format='mixed') # Added format='mixed' here
#ลบวันที่ที่ซ้ำโดยเรียงจากวันที่และสนจากค่าpm25ที่ใกล้เคียงก่อน
df = (
    df.sort_values(by='pm25', na_position='last')
      .drop_duplicates(subset=['date'], keep='first')
           .sort_values(by='date')
)
# ตั้ง rule
df.loc[df['prcp'] < 0, 'prcp'] = None

# เติมด้วยค่าเฉลี่ย
df['pm25'] = df['pm25'].fillna(df['pm25'].mean())

display(df)

display(df)